language: ruby
rvm:
  - 1.9.3
# TODO  - jruby-19mode # JRuby in 1.9 mode

env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql
  - GEONAMES_USER=chromotype_ci

before_script:
  - sudo apt-get install graphicsmagick
#  - mysql -e 'create database chromotype_test'
  - psql -c 'create database chromotype_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
