sudo: required
dist: trusty
language: ruby

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    
cache: bundler
rvm:
  - 2.1.2

env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql

before_script:
  - sudo apt-get install graphicsmagick -y
  - mysql -e 'create database chromotype_test'
  - psql -c 'create database chromotype_test' -U postgres

script:
  - GEONAMES_USER=chromotype_ci RAILS_ENV=test bundle exec rake --trace db:migrate test:all
