sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: ps_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password: postgres
  database: ps_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  <<: *<%= ENV['DB'] || "postgresql" %>

# TODO: would it be cleaner to just monkeypatch rails' database.yml reader?

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
