sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: chromotype_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: chromotype_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

# TODO: would it be cleaner to just monkeypatch rails' database.yml reader?

development:
  <<: *defaults

test:
  adapter: sqlite3 # because travis CI does "sanity checking" without ERB.
  <<: *defaults

production:
  <<: *defaults
  # presumably, we'd erb-echo the production password from /etc/something here.